sonar.projectKey=collector-shop
sonar.projectName=collector-shop
sonar.sourceEncoding=UTF-8

sonar.sources=frontend,backend
sonar.tests=frontend,backend

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/playwright-report/**,**/test-results/**
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/*.e2e-spec.ts,frontend/tests/e2e/**/*.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
