apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collector-dev-local
  namespace: argocd
spec:
  project: collector
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: shared-secrets
      namespace: collector-dev-local
      jsonPointers:
        - /data/RESEND_API_KEY
  source:
    repoURL: https://github.com/louis-cardon/collector.git
    targetRevision: develop
    path: infra/k8s/overlays/dev-local
  destination:
    server: https://kubernetes.default.svc
    namespace: collector-dev-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
