apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collector-prod
  namespace: argocd
spec:
  project: collector
  source:
    repoURL: https://github.com/louis-cardon/collector.git
    targetRevision: main
    path: infra/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: collector-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
