apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: collector-dev

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: frontend-config
    literals:
      - NEXT_PUBLIC_API_BASE_URL=/api
  - name: api-gateway-config
    literals:
      - PORT=3001
      - LOG_LEVEL=debug
      - CORS_ALLOWED_ORIGINS=http://collector.dev.local,http://collector.dev.local:8081,http://localhost:3000,http://127.0.0.1:3000
      - AUTH_SERVICE_URL=http://auth-service:3002
      - CATALOG_SERVICE_URL=http://catalog-service:3003
      - ARTICLE_SERVICE_URL=http://article-service:3004
      - AUDIT_SERVICE_URL=http://audit-service:3005
  - name: auth-service-config
    literals:
      - PORT=3002
      - LOG_LEVEL=debug
      - JWT_EXPIRES_IN=1h
      - AUDIT_SERVICE_URL=http://audit-service:3005
  - name: catalog-service-config
    literals:
      - PORT=3003
      - LOG_LEVEL=debug
      - AUDIT_SERVICE_URL=http://audit-service:3005
  - name: article-service-config
    literals:
      - PORT=3004
      - LOG_LEVEL=debug
      - AUDIT_SERVICE_URL=http://audit-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3006
  - name: audit-service-config
    literals:
      - PORT=3005
      - LOG_LEVEL=debug
  - name: notification-service-config
    literals:
      - PORT=3006
      - LOG_LEVEL=debug
      - AUTH_SERVICE_URL=http://auth-service:3002
      - NOTIFICATIONS_PROVIDER=logger
      - NOTIFICATIONS_FROM_EMAIL=no-reply@collector.dev.local
      - NOTIFICATIONS_TEST_RECIPIENT=

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: collector/api-gateway:latest
    newName: ghcr.io/louis-cardon/collector-api-gateway
    newTag: develop-36a94b282909
  - name: collector/auth-service:latest
    newName: ghcr.io/louis-cardon/collector-auth-service
    newTag: develop-36a94b282909
  - name: collector/catalog-service:latest
    newName: ghcr.io/louis-cardon/collector-catalog-service
    newTag: develop-36a94b282909
  - name: collector/article-service:latest
    newName: ghcr.io/louis-cardon/collector-article-service
    newTag: develop-36a94b282909
  - name: collector/audit-service:latest
    newName: ghcr.io/louis-cardon/collector-audit-service
    newTag: develop-36a94b282909
  - name: collector/notification-service:latest
    newName: ghcr.io/louis-cardon/collector-notification-service
    newTag: develop-36a94b282909
  - name: collector/frontend:latest
    newName: ghcr.io/louis-cardon/collector-frontend
    newTag: develop-36a94b282909

patches:
  - path: patch-image-pull.yaml
  - path: patch-ingress.yaml
